"use client";

import { useEffect, useMemo, useState } from "react";
import { SubPage, ComponentConfig, SEOConfig } from "@/types/landing";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import SEOEditor from "@/components/editor/editors/fields/SEOEditor";
import { validateOpenGraphImages } from "@/lib/field-validators";

interface SubPageFormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  // null = creating a new page; a SubPage = editing that page's metadata
  subPageToEdit: SubPage | null;
  existingSubPages: SubPage[];
  mainPageComponents?: ComponentConfig[]; // Template components to inherit on create
  onSave: (subPage: SubPage) => void;
}

const generateSlug = (title: string) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

export default function SubPageFormDialog({
  open,
  onOpenChange,
  subPageToEdit,
  existingSubPages,
  mainPageComponents = [],
  onSave,
}: SubPageFormDialogProps) {
  const [formData, setFormData] = useState({
    title: "",
    slug: "",
    icon: "",
    description: "",
  });
  const [seoConfig, setSeoConfig] = useState<SEOConfig>({
    metaTitle: "",
    metaDescription: "",
    keywords: [],
  });

  // Re-seed the form whenever the dialog opens or the target page changes,
  // instead of relying on internally-owned open state.
  useEffect(() => {
    if (!open) return;

    setFormData(
      subPageToEdit
        ? {
            title: subPageToEdit.title,
            slug: subPageToEdit.slug,
            icon: subPageToEdit.icon || "",
            description: subPageToEdit.description || "",
          }
        : { title: "", slug: "", icon: "", description: "" }
    );

    // Sub-pages created before per-page SEO existed (or never edited since)
    // don't have their own seo yet — seed from title/description so the
    // fields aren't blank, same fallback PageSettingsModal uses for the
    // main page.
    setSeoConfig(
      subPageToEdit?.seo || {
        metaTitle: subPageToEdit?.title || "",
        metaDescription: subPageToEdit?.description || "",
        keywords: [],
      }
    );
  }, [open, subPageToEdit]);

  // Recomputed live from seoConfig — see docs/editor-input-validation-plan.md.
  const ogImageErrors = useMemo(
    () => validateOpenGraphImages(seoConfig.openGraph?.images),
    [seoConfig.openGraph?.images]
  );
  const hasOgImageErrors = Object.keys(ogImageErrors).length > 0;

  const handleTitleChange = (newTitle: string) => {
    // Only auto-derive the slug from the title while it hasn't been manually
    // customized — otherwise editing a title would silently rewrite an
    // already-published subpage's URL.
    const slugIsAutoGenerated =
      !subPageToEdit || formData.slug === generateSlug(subPageToEdit.title);

    setFormData({
      ...formData,
      title: newTitle,
      slug: slugIsAutoGenerated ? generateSlug(newTitle) : formData.slug,
    });
  };

  const handleSave = () => {
    if (!formData.title.trim() || hasOgImageErrors) return;

    // onSave can update the currently-active EditableLandingPage's `page`
    // prop (e.g. when editing the sub-page currently open in the canvas),
    // which resets its state — a big enough change to race this Sheet's own
    // close if fired in the same tick, sometimes leaving Radix's
    // document.body pointer-events lock stuck (whole editor goes
    // unclickable). Close first, defer the save to the next tick.
    const save = subPageToEdit
      ? {
          ...subPageToEdit,
          title: formData.title,
          slug: formData.slug || generateSlug(formData.title),
          icon: formData.icon,
          description: formData.description,
          seo: seoConfig,
        }
      : {
          id: `subpage-${Date.now()}`,
          title: formData.title,
          slug: formData.slug || generateSlug(formData.title),
          icon: formData.icon,
          description: formData.description,
          // Inherit components from the main page (deep copy with new IDs)
          components: mainPageComponents.map((comp, index) => ({
            ...comp,
            id: `comp-${Date.now()}-${index}-${Math.random().toString(36).substr(2, 9)}`,
            order: index,
            config: JSON.parse(JSON.stringify(comp.config)),
          })),
          order: existingSubPages.length,
          visible: true,
          seo: seoConfig,
        };

    setTimeout(() => onSave(save), 0);

    onOpenChange(false);
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full sm:max-w-xl overflow-y-auto">
        <SheetHeader>
          <SheetTitle>{subPageToEdit ? "Chỉnh sửa trang" : "Tạo trang mới"}</SheetTitle>
          <SheetDescription>
            {subPageToEdit
              ? "Cập nhật thông tin và SEO cho trang con"
              : `Thêm một trang con vào landing page. Trang mới sẽ kế thừa ${mainPageComponents.length} components từ trang chính.`}
          </SheetDescription>
        </SheetHeader>

        <Tabs defaultValue="info" className="mt-4">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="info">Thông tin</TabsTrigger>
            <TabsTrigger value="seo">SEO</TabsTrigger>
          </TabsList>

          <TabsContent value="info" className="space-y-4 mt-4">
            <div className="space-y-2">
              <Label htmlFor="title">Tiêu đề *</Label>
              <Input
                id="title"
                value={formData.title}
                onChange={(e) => handleTitleChange(e.target.value)}
                placeholder="Ví dụ: Tính năng"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="slug">Slug *</Label>
              <Input
                id="slug"
                value={formData.slug}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    slug: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""),
                  })
                }
                placeholder="tinh-nang"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="icon">Icon (emoji hoặc tên icon)</Label>
              <Input
                id="icon"
                value={formData.icon}
                onChange={(e) => setFormData({ ...formData, icon: e.target.value })}
                placeholder="🚀 hoặc rocket"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Mô tả</Label>
              <Input
                id="description"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                placeholder="Mô tả ngắn về trang này"
              />
            </div>

            {!subPageToEdit && mainPageComponents.length > 0 && (
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                <p className="text-sm text-blue-800">
                  <strong>💡 Lưu ý:</strong> Trang mới sẽ tự động kế thừa{" "}
                  {mainPageComponents.length} components từ trang chính. Bạn có thể chỉnh sửa sau
                  khi tạo.
                </p>
              </div>
            )}
          </TabsContent>

          <TabsContent value="seo" className="mt-4">
            <SEOEditor config={seoConfig} onChange={setSeoConfig} ogImageErrors={ogImageErrors} />
          </TabsContent>
        </Tabs>

        <SheetFooter className="mt-4">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Hủy
          </Button>
          <Button onClick={handleSave} disabled={!formData.title.trim() || hasOgImageErrors}>
            {subPageToEdit ? "Cập nhật" : "Tạo"}
          </Button>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}
