"use client";

import { useEffect, useState } from "react";
import { SubPage, ComponentConfig } from "@/types/landing";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface SubPageFormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  // null = creating a new page; a SubPage = editing that page's metadata
  subPageToEdit: SubPage | null;
  existingSubPages: SubPage[];
  mainPageComponents?: ComponentConfig[]; // Template components to inherit on create
  onSave: (subPage: SubPage) => void;
}

const generateSlug = (title: string) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

export default function SubPageFormDialog({
  open,
  onOpenChange,
  subPageToEdit,
  existingSubPages,
  mainPageComponents = [],
  onSave,
}: SubPageFormDialogProps) {
  const [formData, setFormData] = useState({
    title: "",
    slug: "",
    icon: "",
    description: "",
  });

  // Re-seed the form whenever the dialog opens or the target page changes,
  // instead of relying on internally-owned open state.
  useEffect(() => {
    if (!open) return;

    setFormData(
      subPageToEdit
        ? {
            title: subPageToEdit.title,
            slug: subPageToEdit.slug,
            icon: subPageToEdit.icon || "",
            description: subPageToEdit.description || "",
          }
        : { title: "", slug: "", icon: "", description: "" }
    );
  }, [open, subPageToEdit]);

  const handleTitleChange = (newTitle: string) => {
    // Only auto-derive the slug from the title while it hasn't been manually
    // customized — otherwise editing a title would silently rewrite an
    // already-published subpage's URL.
    const slugIsAutoGenerated =
      !subPageToEdit || formData.slug === generateSlug(subPageToEdit.title);

    setFormData({
      ...formData,
      title: newTitle,
      slug: slugIsAutoGenerated ? generateSlug(newTitle) : formData.slug,
    });
  };

  const handleSave = () => {
    if (!formData.title.trim()) return;

    if (subPageToEdit) {
      onSave({
        ...subPageToEdit,
        title: formData.title,
        slug: formData.slug || generateSlug(formData.title),
        icon: formData.icon,
        description: formData.description,
      });
    } else {
      // Inherit components from the main page (deep copy with new IDs)
      const inheritedComponents = mainPageComponents.map((comp, index) => ({
        ...comp,
        id: `comp-${Date.now()}-${index}-${Math.random().toString(36).substr(2, 9)}`,
        order: index,
        config: JSON.parse(JSON.stringify(comp.config)),
      }));

      onSave({
        id: `subpage-${Date.now()}`,
        title: formData.title,
        slug: formData.slug || generateSlug(formData.title),
        icon: formData.icon,
        description: formData.description,
        components: inheritedComponents,
        order: existingSubPages.length,
        visible: true,
      });
    }

    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{subPageToEdit ? "Chỉnh sửa trang" : "Tạo trang mới"}</DialogTitle>
          <DialogDescription>
            {subPageToEdit
              ? "Cập nhật thông tin trang con"
              : `Thêm một trang con vào landing page. Trang mới sẽ kế thừa ${mainPageComponents.length} components từ trang chính.`}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="title">Tiêu đề *</Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => handleTitleChange(e.target.value)}
              placeholder="Ví dụ: Tính năng"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">Slug *</Label>
            <Input
              id="slug"
              value={formData.slug}
              onChange={(e) =>
                setFormData({
                  ...formData,
                  slug: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""),
                })
              }
              placeholder="tinh-nang"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="icon">Icon (emoji hoặc tên icon)</Label>
            <Input
              id="icon"
              value={formData.icon}
              onChange={(e) => setFormData({ ...formData, icon: e.target.value })}
              placeholder="🚀 hoặc rocket"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Mô tả</Label>
            <Input
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Mô tả ngắn về trang này"
            />
          </div>

          {!subPageToEdit && mainPageComponents.length > 0 && (
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
              <p className="text-sm text-blue-800">
                <strong>💡 Lưu ý:</strong> Trang mới sẽ tự động kế thừa {mainPageComponents.length}{" "}
                components từ trang chính. Bạn có thể chỉnh sửa sau khi tạo.
              </p>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Hủy
          </Button>
          <Button onClick={handleSave} disabled={!formData.title.trim()}>
            {subPageToEdit ? "Cập nhật" : "Tạo"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
